states = {
    'Andhra Pradesh': {
        'capital': 'Amaravati',
        'language': 'Telugu, Urdu',
        'population': 49577103,
        'population_rank': 10,
        'area_sq_km': 162968,
        'area_rank': 7,
        'gdp_usd_billion': 160,
        'gdp_rank': 7,
        'sex_ratio_females_per_1000_males': 993,
        'chief_minister': 'Y.S. Jagan Mohan Reddy',
        'ruling_party': 'YSR Congress Party',
        'number_of_districts': 13
    },
    'Arunachal Pradesh': {
        'capital': 'Itanagar',
        'language': 'English',
        'population': 1383727,
        'population_rank': 27,
        'area_sq_km': 83743,
        'area_rank': 14,
        'gdp_usd_billion': 3,
        'gdp_rank': 28,
        'sex_ratio_females_per_1000_males': 938,
        'chief_minister': 'Pema Khandu',
        'ruling_party': 'BJP',
        'number_of_districts': 25
    },
    'Assam': {
        'capital': 'Dispur',
        'language': 'Assamese',
        'population': 35607039,
        'population_rank': 15,
        'area_sq_km': 78438,
        'area_rank': 16,
        'gdp_usd_billion': 55,
        'gdp_rank': 17,
        'sex_ratio_females_per_1000_males': 958,
        'chief_minister': 'Himanta Biswa Sarma',
        'ruling_party': 'BJP',
        'number_of_districts': 35
    },
    'Bihar': {
        'capital': 'Patna',
        'language': 'Hindi',
        'population': 104099452,
        'population_rank': 3,
        'area_sq_km': 94163,
        'area_rank': 12,
        'gdp_usd_billion': 84,
        'gdp_rank': 9,
        'sex_ratio_females_per_1000_males': 918,
        'chief_minister': 'Nitish Kumar',
        'ruling_party': 'Janata Dal (United)',
        'number_of_districts': 38
    },
    'Chhattisgarh': {
        'capital': 'Raipur',
        'language': 'Hindi',
        'population': 25545198,
        'population_rank': 17,
        'area_sq_km': 135192,
        'area_rank': 9,
        'gdp_usd_billion': 29,
        'gdp_rank': 20,
        'sex_ratio_females_per_1000_males': 991,
        'chief_minister': 'Bhupesh Baghel',
        'ruling_party': 'INC',
        'number_of_districts': 33
    },
    'Goa': {
        'capital': 'Panaji',
        'language': 'Konkani',
        'population': 1458545,
        'population_rank': 26,
        'area_sq_km': 3702,
        'area_rank': 28,
        'gdp_usd_billion': 14,
        'gdp_rank': 25,
        'sex_ratio_females_per_1000_males': 976,
        'chief_minister': 'Pramod Sawant',
        'ruling_party': 'BJP',
        'number_of_districts': 2
    },
    'Gujarat': {
        'capital': 'Gandhinagar',
        'language': 'Gujarati',
        'population': 60439692,
        'population_rank': 9,
        'area_sq_km': 196024,
        'area_rank': 6,
        'gdp_usd_billion': 150,
        'gdp_rank': 6,
        'sex_ratio_females_per_1000_males': 919,
        'chief_minister': 'Bhupendrabhai Patel',
        'ruling_party': 'BJP',
        'number_of_districts': 33
    },
    'Haryana': {
        'capital': 'Chandigarh',
        'language': 'Hindi',
        'population': 25351462,
        'population_rank': 18,
        'area_sq_km': 44212,
        'area_rank': 21,
        'gdp_usd_billion': 40,
        'gdp_rank': 16,
        'sex_ratio_females_per_1000_males': 879,
        'chief_minister': 'Manohar Lal Khattar',
        'ruling_party': 'BJP',
        'number_of_districts': 22
    },
    'Himachal Pradesh': {
        'capital': 'Shimla',
        'language': 'Hindi',
        'population': 6864602,
        'population_rank': 22,
        'area_sq_km': 55673,
        'area_rank': 19,
        'gdp_usd_billion': 13,
        'gdp_rank': 26,
        'sex_ratio_females_per_1000_males': 972,
        'chief_minister': 'Jai Ram Thakur',
        'ruling_party': 'BJP',
        'number_of_districts': 12
    },
    'Jharkhand': {
        'capital': 'Ranchi',
        'language': 'Hindi',
        'population': 32988134,
        'population_rank': 14,
        'area_sq_km': 79714,
        'area_rank': 15,
        'gdp_usd_billion': 33,
        'gdp_rank': 19,
        'sex_ratio_females_per_1000_males': 948,
        'chief_minister': 'Hemant Soren',
        'ruling_party': 'JMM-Congress-RJD',
        'number_of_districts': 24
    },
    'Karnataka': {
        'capital': 'Bengaluru',
        'language': 'Kannada',
        'population': 61095297,
        'population_rank': 8,
        'area_sq_km': 191791,
        'area_rank': 7,
        'gdp_usd_billion': 140,
        'gdp_rank': 4,
        'sex_ratio_females_per_1000_males': 973,
        'chief_minister': 'Basavaraj Bommai',
        'ruling_party': 'BJP',
        'number_of_districts': 31
    },
    'Kerala': {
        'capital': 'Thiruvananthapuram',
        'language': 'Malayalam',
        'population': 33406061,
        'population_rank': 13,
        'area_sq_km': 38863,
        'area_rank': 21,
        'gdp_usd_billion': 30,
        'gdp_rank': 18,
        'sex_ratio_females_per_1000_males': 1084,
        'chief_minister': 'Pinarayi Vijayan',
        'ruling_party': 'CPIM',
        'number_of_districts': 14
    },
    'Madhya Pradesh': {
        'capital': 'Bhopal',
        'language': 'Hindi',
        'population': 72626809,
        'population_rank': 5,
        'area_sq_km': 308350,
        'area_rank': 5,
        'gdp_usd_billion': 95,
        'gdp_rank': 8,
        'sex_ratio_females_per_1000_males': 931,
        'chief_minister': 'Shivraj Singh Chouhan',
        'ruling_party': 'BJP',
        'number_of_districts': 52
    },
    'Maharashtra': {
        'capital': 'Mumbai',
        'language': 'Marathi',
        'population': 112374333,
        'population_rank': 2,
        'area_sq_km': 307713,
        'area_rank': 3,
        'gdp_usd_billion': 420,
        'gdp_rank': 2,
        'sex_ratio_females_per_1000_males': 929,
        'chief_minister': 'Eknath Shinde',
        'ruling_party': 'Shiv Sena(BJP alliance)',
        'number_of_districts': 36
    },
    'Manipur': {
        'capital': 'Imphal',
        'language': 'Meitei',
        'population': 2855794,
        'population_rank': 25,
        'area_sq_km': 22327,
        'area_rank': 23,
        'gdp_usd_billion': 4,
        'gdp_rank': 27,
        'sex_ratio_females_per_1000_males': 985,
        'chief_minister': 'N Biren Singh',
        'ruling_party': 'BJP',
        'number_of_districts': 16
    },
    'Meghalaya': {
        'capital': 'Shillong',
        'language': 'Khasi, Garo',
        'population': 2966889,
        'population_rank': 24,
        'area_sq_km': 22429,
        'area_rank': 22,
        'gdp_usd_billion': 3,
        'gdp_rank': 29,
        'sex_ratio_females_per_1000_males': 986,
        'chief_minister': 'Conrad Sangma',
        'ruling_party': 'NPP',
        'number_of_districts': 11
    },
    'Mizoram': {
        'capital': 'Aizawl',
        'language': 'Mizo',
        'population': 1091014,
        'population_rank': 28,
        'area_sq_km': 21081,
        'area_rank': 24,
        'gdp_usd_billion': 2,
        'gdp_rank': 31,
        'sex_ratio_females_per_1000_males': 976,
        'chief_minister': 'Zoramthanga',
        'ruling_party': 'MNF',
        'number_of_districts': 11
    },
    'Nagaland': {
        'capital': 'Kohima',
        'language': 'English',
        'population': 1978502,
        'population_rank': 26,
        'area_sq_km': 16579,
        'area_rank': 25,
        'gdp_usd_billion': 3,
        'gdp_rank': 30,
        'sex_ratio_females_per_1000_males': 931,
        'chief_minister': 'Neiphiu Rio',
        'ruling_party': 'NDPP',
        'number_of_districts': 12
    },
    'Odisha': {
        'capital': 'Bhubaneswar',
        'language': 'Odia',
        'population': 41974218,
        'population_rank': 11,
        'area_sq_km': 155707,
        'area_rank': 8,
        'gdp_usd_billion': 50,
        'gdp_rank': 14,
        'sex_ratio_females_per_1000_males': 979,
        'chief_minister': 'Naveen Patnaik',
        'ruling_party': 'BJD',
        'number_of_districts': 30
    },
    'Punjab': {
        'capital': 'Chandigarh',
        'language': 'Punjabi',
        'population': 27743338,
        'population_rank': 16,
        'area_sq_km': 50362,
        'area_rank': 20,
        'gdp_usd_billion': 60,
        'gdp_rank': 11,
        'sex_ratio_females_per_1000_males': 895,
        'chief_minister': 'Bhagwant Mann',
        'ruling_party': 'AAP',
        'number_of_districts': 22
    },
    'Rajasthan': {
        'capital': 'Jaipur',
        'language': 'Hindi',
        'population': 68548437,
        'population_rank': 7,
        'area_sq_km': 342239,
        'area_rank': 1,
        'gdp_usd_billion': 110,
        'gdp_rank': 5,
        'sex_ratio_females_per_1000_males': 928,
        'chief_minister': 'Ashok Gehlot',
        'ruling_party': 'INC',
        'number_of_districts': 33
    },
    'Sikkim': {
        'capital': 'Gangtok',
        'language': 'Nepali, Bhutia, Lepcha',
        'population': 610577,
        'population_rank': 29,
        'area_sq_km': 7096,
        'area_rank': 27,
        'gdp_usd_billion': 3,
        'gdp_rank': 32,
        'sex_ratio_females_per_1000_males': 889,
        'chief_minister': 'Prem Singh Tamang',
        'ruling_party': 'SKM',
        'number_of_districts': 6
    },
    'Tamil Nadu': {
        'capital': 'Chennai',
        'language': 'Tamil',
        'population': 72147030,
        'population_rank': 6,
        'area_sq_km': 130058,
        'area_rank': 11,
        'gdp_usd_billion': 180,
        'gdp_rank': 3,
        'sex_ratio_females_per_1000_males': 996,
        'chief_minister': 'M.K. Stalin',
        'ruling_party': 'DMK',
        'number_of_districts': 38
    },
    'Telangana': {
        'capital': 'Hyderabad',
        'language': 'Telugu',
        'population': 35003674,
        'population_rank': 12,
        'area_sq_km': 112077,
        'area_rank': 13,
        'gdp_usd_billion': 95,
        'gdp_rank': 7,
        'sex_ratio_females_per_1000_males': 993,
        'chief_minister': 'K. Chandrashekar Rao',
        'ruling_party': 'TRS',
        'number_of_districts': 33
    },
    'Tripura': {
        'capital': 'Agartala',
        'language': 'Bengali',
        'population': 3673917,
        'population_rank': 23,
        'area_sq_km': 10486,
        'area_rank': 26,
        'gdp_usd_billion': 7,
        'gdp_rank': 23,
        'sex_ratio_females_per_1000_males': 961,
        'chief_minister': 'Manik Saha',
        'ruling_party': 'BJP',
        'number_of_districts': 8
    },
    'Uttar Pradesh': {
        'capital': 'Lucknow',
        'language': 'Hindi',
        'population': 199812341,
        'population_rank': 1,
        'area_sq_km': 243286,
        'area_rank': 4,
        'gdp_usd_billion': 270,
        'gdp_rank': 1,
        'sex_ratio_females_per_1000_males': 912,
        'chief_minister': 'Yogi Adityanath',
        'ruling_party': 'BJP',
        'number_of_districts': 75
    },
    'Uttarakhand': {
        'capital': 'Dehradun',
        'language': 'Hindi',
        'population': 10086292,
        'population_rank': 19,
        'area_sq_km': 53483,
        'area_rank': 17,
        'gdp_usd_billion': 26,
        'gdp_rank': 21,
        'sex_ratio_females_per_1000_males': 963,
        'chief_minister': 'Pushkar Singh Dhami',
        'ruling_party': 'BJP',
        'number_of_districts': 13
    },
    'West Bengal': {
        'capital': 'Kolkata',
        'language': 'Bengali',
        'population': 91276115,
        'population_rank': 4,
        'area_sq_km': 88752,
        'area_rank': 15,
        'gdp_usd_billion': 85,
        'gdp_rank': 10,
        'sex_ratio_females_per_1000_males': 950,
        'chief_minister': 'Mamata Banerjee',
        'ruling_party': 'AITC',
        'number_of_districts': 23
    },
    # Union Territories
    'Andaman and Nicobar Islands': {
        'capital': 'Port Blair',
        'language': 'Hindi, English',
        'population': 380581,
        'area_sq_km': 8249,
        'sex_ratio_females_per_1000_males': 876,
        'lieutenant_governor': 'Aditya Nath Das',
        'ruling_party': None,
        'number_of_districts': 3
    },
    'Chandigarh': {
        'capital': 'Chandigarh',
        'language': 'Hindi, Punjabi, English',
        'population': 1055450,
        'area_sq_km': 114,
        'sex_ratio_females_per_1000_males': 818,
        'lieutenant_governor': 'Banwarilal Purohit',
        'ruling_party': None,
        'number_of_districts': 1
    },
    'Dadra and Nagar Haveli and Daman and Diu': {
        'capital': 'Daman',
        'language': 'Hindi, Gujarati',
        'population': 585764,
        'area_sq_km': 603,
        'sex_ratio_females_per_1000_males': 775,
        'lieutenant_governor': 'Praful Khoda Patel',
        'ruling_party': None,
        'number_of_districts': 3
    },
    'Delhi': {
        'capital': 'New Delhi',
        'language': 'Hindi, English',
        'population': 16787941,
        'area_sq_km': 1483,
        'sex_ratio_females_per_1000_males': 868,
        'lieutenant_governor': 'Vinai Kumar Saxena',
        'ruling_party': 'Aam Aadmi Party (AAP)',
        'number_of_districts': 11,
        'chief_minister': 'Arvind Kejriwal'
    },
    'Jammu and Kashmir': {
        'capital': 'Srinagar (Summer), Jammu (Winter)',
        'language': 'Kashmiri, Dogri, Hindi, Urdu, English',
        'population': 12541302,
        'area_sq_km': 55538,
        'sex_ratio_females_per_1000_males': 889,
        'lieutenant_governor': 'Manoj Sinha',
        'ruling_party': None,
        'number_of_districts': 20
    },
    'Ladakh': {
        'capital': 'Leh and Kargil',
        'language': 'Ladakhi, Balti, Hindi, Urdu',
        'population': 289023,
        'area_sq_km': 59146,
        'sex_ratio_females_per_1000_males': 690,
        'lieutenant_governor': 'Radha Krishna Mathur',
        'ruling_party': None,
        'number_of_districts': 2
    },
    'Lakshadweep': {
        'capital': 'Kavaratti',
        'language': 'Malayalam',
        'population': 64473,
        'area_sq_km': 32,
        'sex_ratio_females_per_1000_males': 946,
        'lieutenant_governor': 'Praful Khoda Patel',
        'ruling_party': None,
        'number_of_districts': 1
    },
    'Puducherry': {
        'capital': 'Puducherry',
        'language': 'Tamil, Telugu, Malayalam, French',
        'population': 1247953,
        'area_sq_km': 492,
        'sex_ratio_females_per_1000_males': 1039,
        'lieutenant_governor': 'Ashwani Kumar',
        'ruling_party': 'DMK-Congress alliance',
        'number_of_districts': 4,
        'chief_minister': 'N. Rangasamy'
    }
}
